/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const HabitView = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'checkIns' : IDL.Vec(Time),
});

export const idlService = IDL.Service({
  'addHabit' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'checkIn' : IDL.Func([IDL.Nat], [], []),
  'getHabit' : IDL.Func([IDL.Nat], [HabitView], ['query']),
  'getHabits' : IDL.Func([], [IDL.Vec(HabitView)], ['query']),
  'getHabitsByCheckIns' : IDL.Func([], [IDL.Vec(HabitView)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const HabitView = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'checkIns' : IDL.Vec(Time),
  });
  
  return IDL.Service({
    'addHabit' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'checkIn' : IDL.Func([IDL.Nat], [], []),
    'getHabit' : IDL.Func([IDL.Nat], [HabitView], ['query']),
    'getHabits' : IDL.Func([], [IDL.Vec(HabitView)], ['query']),
    'getHabitsByCheckIns' : IDL.Func([], [IDL.Vec(HabitView)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };